version: '3.9'

services:
  coredhcp:
    image: unofficial/coredhcp:latest
    restart: unless-stopped
    container_name: coredhcp
    build:
      context: ../
    network_mode: "host"
    volumes:
      - ./config.yml:/app/config.yml
      - ./leases.txt:/app/leases.txt
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
